name: Watermelons are awesome

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        run: echo "Hello world!"
      - name: Get Node versions
        run: |
          node -v 
          npm -v 